"""initial schema

Revision ID: f78ab39c10e6
Revises: 
Create Date: 2026-08-22 17:06:21.601038

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'f78ab39c10e6'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('categories',
    sa.Column('slug', sa.String(length=40), nullable=False),
    sa.Column('label_uz', sa.String(), nullable=False),
    sa.Column('sort_order', sa.Integer(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('slug')
    )
    op.create_table('departments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hemis_id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('code', sa.String(), nullable=True),
    sa.Column('parent_department_id', sa.BigInteger(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['parent_department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_departments_hemis_id'), 'departments', ['hemis_id'], unique=True)
    op.create_table('users',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('email', sa.String(), nullable=False),
    sa.Column('password_hash', sa.String(), nullable=False),
    sa.Column('role', sa.String(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('last_login_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_users_email'), 'users', ['email'], unique=True)
    op.create_table('employees',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('hemis_id', sa.Integer(), nullable=True),
    sa.Column('employee_id_number', sa.String(), nullable=False),
    sa.Column('full_name', sa.String(), nullable=False),
    sa.Column('department_id', sa.BigInteger(), nullable=True),
    sa.Column('employee_status_code', sa.String(length=10), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('year_of_enter', sa.Integer(), nullable=True),
    sa.Column('image_source_url', sa.String(), nullable=True),
    sa.Column('image_local_path', sa.String(), nullable=True),
    sa.Column('is_rtm_staff', sa.Boolean(), nullable=False),
    sa.Column('access_revoked', sa.Boolean(), nullable=False),
    sa.Column('access_revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('telegram_user_id', sa.BigInteger(), nullable=True),
    sa.Column('telegram_username', sa.String(), nullable=True),
    sa.Column('phone_number', sa.String(), nullable=True),
    sa.Column('verified_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['department_id'], ['departments.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('telegram_user_id')
    )
    op.create_index(op.f('ix_employees_employee_id_number'), 'employees', ['employee_id_number'], unique=True)
    op.create_index(op.f('ix_employees_hemis_id'), 'employees', ['hemis_id'], unique=True)
    op.create_table('hemis_sync_runs',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('triggered_by_user_id', sa.BigInteger(), nullable=False),
    sa.Column('started_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('finished_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('departments_created', sa.Integer(), nullable=False),
    sa.Column('departments_updated', sa.Integer(), nullable=False),
    sa.Column('employees_created', sa.Integer(), nullable=False),
    sa.Column('employees_updated', sa.Integer(), nullable=False),
    sa.Column('employees_revoked', sa.Integer(), nullable=False),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.ForeignKeyConstraint(['triggered_by_user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('requests',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('requester_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('category_slug', sa.String(length=40), nullable=False),
    sa.Column('description', sa.Text(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('source', sa.String(), nullable=False),
    sa.Column('assigned_to_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('assigned_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('deadline_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.Column('completion_note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['assigned_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['assigned_to_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['category_slug'], ['categories.slug'], ),
    sa.ForeignKeyConstraint(['requester_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_requests_assigned_to_employee_id'), 'requests', ['assigned_to_employee_id'], unique=False)
    op.create_index(op.f('ix_requests_requester_employee_id'), 'requests', ['requester_employee_id'], unique=False)
    op.create_index(op.f('ix_requests_status'), 'requests', ['status'], unique=False)
    op.create_table('telegram_link_tokens',
    sa.Column('token', sa.String(length=64), nullable=False),
    sa.Column('employee_id', sa.BigInteger(), nullable=False),
    sa.Column('purpose', sa.String(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=False),
    sa.Column('completed_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('token')
    )
    op.create_index(op.f('ix_telegram_link_tokens_employee_id'), 'telegram_link_tokens', ['employee_id'], unique=False)
    op.create_table('ratings',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('rated_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('rated_by_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('score', sa.SmallInteger(), nullable=False),
    sa.Column('comment', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.CheckConstraint('score >= 1 AND score <= 5', name='ck_ratings_score_1_5'),
    sa.ForeignKeyConstraint(['rated_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['rated_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('request_id')
    )
    op.create_index(op.f('ix_ratings_rated_employee_id'), 'ratings', ['rated_employee_id'], unique=False)
    op.create_table('request_attachments',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('uploaded_by_employee_id', sa.BigInteger(), nullable=False),
    sa.Column('file_path', sa.String(), nullable=False),
    sa.Column('original_filename', sa.String(), nullable=True),
    sa.Column('content_type', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.ForeignKeyConstraint(['uploaded_by_employee_id'], ['employees.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_attachments_request_id'), 'request_attachments', ['request_id'], unique=False)
    op.create_table('request_messages',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('author_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('author_user_id', sa.BigInteger(), nullable=True),
    sa.Column('visibility', sa.String(), nullable=False),
    sa.Column('body', sa.Text(), nullable=False),
    sa.Column('telegram_message_id', sa.BigInteger(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['author_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['author_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_messages_request_id'), 'request_messages', ['request_id'], unique=False)
    op.create_table('request_status_history',
    sa.Column('id', sa.BigInteger(), nullable=False),
    sa.Column('request_id', sa.BigInteger(), nullable=False),
    sa.Column('from_status', sa.String(), nullable=True),
    sa.Column('to_status', sa.String(), nullable=False),
    sa.Column('changed_by_employee_id', sa.BigInteger(), nullable=True),
    sa.Column('changed_by_user_id', sa.BigInteger(), nullable=True),
    sa.Column('note', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.ForeignKeyConstraint(['changed_by_employee_id'], ['employees.id'], ),
    sa.ForeignKeyConstraint(['changed_by_user_id'], ['users.id'], ),
    sa.ForeignKeyConstraint(['request_id'], ['requests.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_request_status_history_request_id'), 'request_status_history', ['request_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_request_status_history_request_id'), table_name='request_status_history')
    op.drop_table('request_status_history')
    op.drop_index(op.f('ix_request_messages_request_id'), table_name='request_messages')
    op.drop_table('request_messages')
    op.drop_index(op.f('ix_request_attachments_request_id'), table_name='request_attachments')
    op.drop_table('request_attachments')
    op.drop_index(op.f('ix_ratings_rated_employee_id'), table_name='ratings')
    op.drop_table('ratings')
    op.drop_index(op.f('ix_telegram_link_tokens_employee_id'), table_name='telegram_link_tokens')
    op.drop_table('telegram_link_tokens')
    op.drop_index(op.f('ix_requests_status'), table_name='requests')
    op.drop_index(op.f('ix_requests_requester_employee_id'), table_name='requests')
    op.drop_index(op.f('ix_requests_assigned_to_employee_id'), table_name='requests')
    op.drop_table('requests')
    op.drop_table('hemis_sync_runs')
    op.drop_index(op.f('ix_employees_hemis_id'), table_name='employees')
    op.drop_index(op.f('ix_employees_employee_id_number'), table_name='employees')
    op.drop_table('employees')
    op.drop_index(op.f('ix_users_email'), table_name='users')
    op.drop_table('users')
    op.drop_index(op.f('ix_departments_hemis_id'), table_name='departments')
    op.drop_table('departments')
    op.drop_table('categories')
    # ### end Alembic commands ###
